CREATE TABLE IF NOT EXISTS COMPANY (
	ComName varchar(40) NOT NULL,
	ComId int(20) NOT NULL,
	PRIMARY KEY(ComID)
);

INSERT INTO COMPANY(ComName, ComID) VALUES ('c', 0);

CREATE TABLE IF NOT EXISTS MEMBER (
	ID INT NOT NULL UNIQUE AUTO_INCREMENT, 
	ACCID VARCHAR(30) NOT NULL UNIQUE, 
	PWD VARCHAR(30) NOT NULL,
	OAUTHID VARCHAR(30) NULL,
	ComId INT DEFAULT 0,
	PRIMARY KEY(ID),
	FOREIGN KEY MEMBER(ComId) REFERENCES COMPANY(ComID)
	);

CREATE TABLE IF NOT EXISTS CARD (
	ComId int(20) NOT NULL,
	CardNum int(10) NOT NULL,
	CardType varchar(20) NOT NULL,
	ExpireTime varchar(20) NOT NULL,
	NationId varchar(11) NOT NULL,
	CardLevel varchar(20) NOT NULL,
	Phone BIGINT NOT NULL,
	AccId varchar(20) NOT NULL,
	PRIMARY KEY(ComId, CardNum)
);

CREATE TABLE  IF NOT EXISTS TRANSAC (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COMID INT NOT NULL,
    CARDNUM INT NOT NULL,
    TRANSCODE VARCHAR(20) NOT NULL,
    EXPIRE INT NOT NULL,
    FOREIGN KEY TRANSAC(COMID, CARDNUM) REFERENCES CARD(ComId, CardNum)
);

CREATE TABLE IF NOT EXISTS TransLog (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CreateTime TIMESTAMP NOT NULL,
	ComID INT(20) NOT NULL,
	CardNum INT(10) NOT NULL,
	TRANSCODE VARCHAR(20) NOT NULL,
	CLIENT INT NOT NULL,
	ADMIN INT NOT NULL
);

INSERT INTO COMPANY(ComName, ComID) VALUES ('testCompany', 2);
INSERT INTO MEMBER(ACCID, PWD) VALUES ('test', 'test');
INSERT INTO MEMBER(ACCID, PWD, ComId) VALUES ('admin', 'admin', 2);
INSERT INTO CARD VALUES (2, 111, "Permanent", '-1', 'S123123123', 'N', '123123123', 1);
INSERT INTO CARD VALUES (2, 112, "Limited", '1486684799', 'S123123123', 'N', '123123123', 1);
INSERT INTO CARD VALUES (2, 113, "Times", '20/30', 'S123123123', 'N', '123123123', 1);