CREATE TABLE MEMBER (
	ID INT NOT NULL UNIQUE AUTO_INCREMENT, 
	ACCID VARCHAR(30) NOT NULL UNIQUE, 
	PWD VARCHAR(30) NOT NULL,
	OAUTHID VARCHAR(30) NULL,
	PRIMARY KEY(ID)
	);

CREATE TABLE TRANSAC (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COMID INT NOT NULL,
    CARDNUM INT NOT NULL,
    TRANSCODE VARCHAR(20) NOT NULL,
    EXPIRE INT NOT NULL,
    FOREIGN KEY TRANSAC (COMID, CARDNUM) REFERENCES CARD(ComId, CardNum)
);